### ISSUE TITLE
Suggestions for Equivalent width student version

### ISSUE THREAD

**Issue by astroDimitrios** [jimmynewland/colabnotebooks#1]
Looking at the Student version of the Equivalent width spec - some thoughts:

- Do your students know how to use notebooks/colab? The Using Google Colab section seems to imply they don't but it doesn't say how to run a code cell or exit a text block you've edited in the text - it only mentions the play button as a comment in the code cell.

- You ask for answers to questions in the same markdown cell as the question - if you make this separate then the question would stay formatted while they type their answers?

- Could you elaborate on the spectrograph image? Is it the brown box? The white box, maybe both?

- Line: "Spectroscopy can tell us objects in space." - what are you trying to say?

- What is the purpose of the Eu Abundance Ratio image? Without a caption it is hard to understand.

- At the start of the Plotting the Spectrum of Each Star section you have a code cell and then immediately have instructions ("Add..."). I found this confusing - could you take out the multiline comment and put it in the markdown cell above? Then leave a simpler docstring in your function?

- The relative flux y-axis label is missing units.

- Two hints formatted differently for Q3?

- What are the other symbols in the equivalent width equation?

- Question 4 and 5 are the same? Do you want them to do it by eye for two different plots?

- Just before Q6 you are printing out a table with data you calculated - would it be more readable if you formatted the output using string formatting not with str() and tabs?

- Is there are reason you start at Q0 not Q1?

Great Notebook! I've never heard of SpecUtils before - will have to check it out.

**Comment by jimmynewland** [comment]
I think I'm going to roll all of these comments into this version before I assign this project. I also think I'll make a video explainer for using Google Colab/Jupyter notebook/Markdown.
